[package]
name = "python-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/unicode-xid"]

[dependencies]
bitflags = "1.3.2"
encoding_rs = "0.8.32"
unicode-ident = "1.0.8"
unicode-xid = { path = "crates/unicode-xid", package = "unicode-xid" }

[dev-dependencies]
pretty_assertions = "1.3.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
