[package]
name = "python_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
ruff_python_resolver = { workspace = true }
python_ast = { workspace = true }
anyhow = { workspace = true }
